# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_raw', '0002_auto_20160703_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatafile',
            name='clean_file_size',
            field=models.IntegerField(default=0, help_text='Size of the .CSV file', verbose_name='size of clean data file in bytes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='download_file_size',
            field=models.IntegerField(default=0, help_text='Size of the .TSV file', verbose_name='size of raw data file in bytes'),
            preserve_default=False,
        ),
    ]
