# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 05:18
from __future__ import unicode_literals

import calaccess_raw
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calaccess_raw', '0007_rawdatafile_error_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatafile',
            name='error_log_archive',
            field=models.FileField(blank=True, help_text='An archive of the error log containing lines from the original download file that could not be parsed and are excluded from the cleaned file.', max_length=255, upload_to=calaccess_raw.archive_directory_path, verbose_name='archive of error log'),
        ),
    ]
